### ISSUE TITLE
Add an sleep setting

### ISSUE THREAD

**Issue by eracknaphobia** [mdegat01/addon-amr2mqtt#82]
**Is your feature request related to a problem? Please describe.**

The R900 I use for reading my water meter consumes a lot of CPU  and I don't really need a down to the minute reading on water consumption.

**Describe the solution you'd like**

Add an optional setting to the meter configuration to sleep for x seconds after a message is received

```
meters:
  - id: 12345678
    protocol: scm
    name: My gas meter
    type: gas
    multiplier: 0.01
    unit_of_measurement: ccf
    sleep_interval: 3600
```
